{
  "openapi": "3.1.0",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/recipe": {
      "get": {
        "tags": [
          "recipe-controller"
        ],
        "summary": "Get all recipes",
        "operationId": "getRecipes",
        "responses": {
          "200": {
            "description": "Recipes retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Recipe"
                }
              }
            }
          }
        }
      }
    },
    "/recipe/{recipeName}": {
      "get": {
        "tags": [
          "recipe-controller"
        ],
        "summary": "Get recipe by name",
        "operationId": "getRecipe",
        "parameters": [
          {
            "name": "recipeName",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Recipe retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Recipe"
                }
              }
            }
          }
        }
      }
    },
    "/recipe/{recipeName}/instructions": {
      "get": {
        "tags": [
          "recipe-controller"
        ],
        "summary": "Get recipe instructions by name",
        "operationId": "getRecipeInstructions",
        "parameters": [
          {
            "name": "recipeName",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Recipe instructions retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Recipe": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "yield": {
            "type": "integer",
            "format": "int32"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}